### ISSUE TITLE
Does not work in ARM machines

### ISSUE THREAD

**Issue by anistark** [iotaledger/iota.lib.js#1138]
## Bug description

Has problem while installing in machines with ARM architecture, specially, Apple M1 silicon machines.
`npm i @iota/pow-neon.js@next @iota/util.js@next -S` throws error as :

## Hardware specification

What hardware are you using?

- Operating system: macOS Monterey v12.5
- RAM: 16GB
- Number of cores: 8
- Device type: MacBook Pro

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Install : `npm i @iota/pow-neon.js@next @iota/util.js@next -S`

## Expected behaviour

Should install.

## Actual behaviour

Throws error while installing

## Errors

```sh
npm ERR!   2 warnings and 3 errors generated.
npm ERR!   make: *** [Release/obj.target/neon/src/neon.o] Error 1
npm ERR!   gyp ERR! build error
npm ERR!   gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR!   gyp ERR! stack     at ChildProcess.onExit (/.../node_modules/@iota/pow-neon.js/native/target/release/build/neon-sys-0bd3d273171d2603/out/native/node_modules/node-gyp/lib/build.js:194:23)
npm ERR!   gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR!   gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR!   gyp ERR! System Darwin 21.6.0
npm ERR!   gyp ERR! command "/Users/ani/.nvm/versions/node/v18.12.0/bin/node" "/.../node_modules/@iota/pow-neon.js/native/target/release/build/neon-sys-0bd3d273171d2603/out/native/node_modules/.bin/node-gyp" "build" "--verbose"
npm ERR!   gyp ERR! cwd /.../node_modules/@iota/pow-neon.js/native/target/release/build/neon-sys-0bd3d273171d2603/out/native
npm ERR!   gyp ERR! node -v v18.12.0
npm ERR!   gyp ERR! node-gyp -v v7.1.2
npm ERR!   gyp ERR! not ok
npm ERR!   ', /Users/ani/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-sys-0.8.3/build.rs:209:13
npm ERR!   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
npm ERR! neon ERR! cargo build failed
npm ERR!
npm ERR! Error: cargo build failed
npm ERR!     at Target.<anonymous> (/.../node_modules/neon-cli/lib/target.js:99:27)
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at fulfilled (/.../node_modules/neon-cli/lib/target.js:24:58)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by msarcev** [comment]
Hello @anistark, the libs were tested on M1 macs without issues.
But i managed to reproduce your issue when trying to `npm i` with a newer version of node.
I would suggest not using a node version `> v16` and corresponding npm.
Tested and working with:
node v16.16.0
npm v8.19.2

**Comment by anistark** [comment]
I did try with 16.18.0 but still didn't work. Will try again with 14 later.
