### ISSUE TITLE
PowNeon dependencies failing the build

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota.lib.js#1199]
## Bug description

`npm i` is failing on fresh library repo cause of issue in installing `pow-neon` dependencies.

## Version

Which version of the library are you running?
`stardust`

- Version:

## Hardware specification

What hardware are you using?

- Operating system: M1 Mac

## Steps To reproduce the bug

1. Execute `npm i` in the root of the repo (`stardust` branch)

## Expected behaviour

Builds successfully

## Actual behaviour

Exits with error

## Errors

Paste any errors that you see.

```
npm ERR!   gyp ERR! cwd ...stardust/packages/pow-neon/native/target/release/build/neon-sys-56508349f5eff748/out/native
npm ERR!   gyp ERR! node -v v16.16.0
npm ERR!   gyp ERR! node-gyp -v v7.1.2
npm ERR!   gyp ERR! not ok
npm ERR!   ', .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/neon-sys-0.8.3/build.rs:176:13
npm ERR!   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
npm ERR! neon ERR! cargo build failed
npm ERR!
npm ERR! Error: cargo build failed
npm ERR!     at Target.<anonymous> (...node_modules/neon-cli/lib/target.js:99:27)
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at fulfilled (...node_modules/neon-cli/lib/target.js:24:58)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by msarcev** [comment]
The fix is to up the neon related versions in Cargo.toml
```
diff --git a/packages/pow-neon/native/Cargo.toml b/packages/pow-neon/native/Cargo.toml
index 286573e7..66f8d2f3 100644
--- a/packages/pow-neon/native/Cargo.toml
+++ b/packages/pow-neon/native/Cargo.toml
@@ -12,8 +12,8 @@ name = "pow_neon"
 crate-type = ["cdylib"]

 [build-dependencies]
-neon-build = "0.8.1"
+neon-build = "0.10.1"

 [dependencies]
-neon = "0.8.1"
+neon = "0.10.1"
 bee-pow = "0.1"
```

A new version should be released with the fix.
