### ISSUE TITLE
getTransactionsToRequest

### ISSUE THREAD

**Issue by crholliday** [iotaledger/iota.lib.js#154]
Something appears to have happened with a dependency that is breaking `getTransactionsToRequest()`

Running the following 0.4.6:
```
iota.api.getTransactionsToApprove(3, function(err, cb) {
    if(err) {console.log(err)}
    console.log(cb)
})
```
Results in the following error:
```
C:\Users\crhol\OneDrive\dev\iota-promoter\node_modules\iota.lib.js\lib\utils\makeRequest.js:313
 return callback(error, result);
           ^

TypeError: callback is not a function
    at makeRequest.prepareResult (C:\Users\crhol\OneDrive\dev\iota-promoter\node_modules\iota.lib.js\lib\utils\makeRequest.js:313:12)
    at exports.XMLHttpRequest.request.onreadystatechange (C:\Users\crhol\OneDrive\dev\iota-promoter\node_modules\iota.lib.js\lib\utils\makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (C:\Users\crhol\OneDrive\dev\iota-promoter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (C:\Users\crhol\OneDrive\dev\iota-promoter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (C:\Users\crhol\OneDrive\dev\iota-promoter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Prior to version 0.4.4 this works as expected.

**Comment by chrisdukakis** [comment]
There was a change to API, a new `reference` parameter was introduced to enable transaction promotion, but it seems that should be optional. I'll fix it in next release.

A workaround, is to pass `null`:
```
iota.api.getTransactionsToApprove(3, null, function(err, cb) {...})
 ```

**Comment by crholliday** [comment]
Yep, that works... thanks.

I'll open another issue if you want but is that function supposed to take 7-30 seconds to run?

**Comment by chrisdukakis** [comment]
7-30s is a lot, it should take a few ms normally. Did you change the depth from 3? Also please check if your node is syncing, or it isn't just a network issue (check duration in response). Changing node or waiting to sync might help.

**Comment by crholliday** [comment]
I have 3 full nodes, all synced with plenty of resources. I have checked using curl and with the JS api with different depths and the results are the same. I have also had several folks on slack test on their nodes across different depths from 3 - 100 and the results reported have been the same. 

IRI looks like it is bogging down here: https://github.com/iotaledger/iri/blob/3ef29fce7260076659f88e0f10244f4a59edb550/src/main/java/com/iota/iri/service/API.java#L552

**Comment by chrisdukakis** [comment]
Please report this to `iri` repo and include the logs near `getTransactionsToApprove` calls.

**Comment by crholliday** [comment]
Will do.
