### ISSUE TITLE
ERROR Error: Request Error: attempt to unlock read lock, not locked by current thread

### ISSUE THREAD

**Issue by burtonsamograd** [iotaledger/iota.lib.js#172]
```sh
bash-3.2$ ./tangle sendTransfer CMLEIJIWNM9AFVLUJJKIPZXBJATJIGBIWGPNJR9MTZHRHHPDX9RXHDZWCUPCOOYXYJMDACZSTURJWNLYW 'Testing'
// st
ERROR Error: Request Error: attempt to unlock read lock, not locked by current thread
    at Object.requestError (/Users/burton/eth-1/iota.lib.js/lib/errors/requestErrors.js:11:12)
    at makeRequest.prepareResult (/Users/burton/eth-1/iota.lib.js/lib/utils/makeRequest.js:293:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/burton/eth-1/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/Users/burton/eth-1/iota.lib.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/burton/eth-1/iota.lib.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/burton/eth-1/iota.lib.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

with sendTransfer being:

```js
case 'sendTransfer': {
    const Depth = 3; // constant defined by IOTA - how deep to look for the tips in the Tangle                                                                  
    const MinWeightMagnitude = 16; // constant defined by IOTA - the difficulty of PoW                                                                          

    const transfers = [{
            address: process.argv[3],
            value: 0,
            message: iota.utils.toTrytes(process.argv[4])
        }];

    const options = {
    };

    iota.api.sendTransfer(seed, Depth, MinWeightMagnitude, transfers, options, (error, transactions) => {
            if (error) {
                console.error('ERROR', error)
            } else {
                console.log('NO ERROR', transactions)
            }
        })
}
    break;
```

Am I doing something incorrectly with the API?

**Comment by burtonsamograd** [comment]
I'm also seeing:

```
java.lang.RuntimeException: starting tip failed consistency check: 999999999999999999999999999999999999999999999999999999999999999999999999999999999
        at com.iota.iri.service.TipsManager.transactionToApprove(TipsManager.java:122)
        at com.iota.iri.service.API.getTransactionToApproveStatement(API.java:605)
        at com.iota.iri.service.API.process(API.java:290)
        at com.iota.iri.service.API.processRequest(API.java:185)
        at com.iota.iri.service.API.access$000(API.java:68)
        at com.iota.iri.service.API$1.handleRequest(API.java:148)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I'm trying to run my own testnet using the instructions here:

https://forum.iota.org/t/running-a-node-in-isolation-how-to-work-around-the-subtangle-has-not-been-updated-yet-errors/1410/3

**Comment by th0br0** [comment]
@paulhandy @alon-e

**Comment by burtonsamograd** [comment]
I noticed I missed this part:

"You need to either have a milestone in your database already, or you need to comment out the block in API.java that prevents you from getting transactions to approve when there are none available."

How does one put a milestone in the database manually?

**Comment by AaronVasquez** [comment]
Im running into the same problem. Has there been any updates to resolve this?

**Comment by burtonsamograd** [comment]
@paulhandy I've asked for assistance in the IOTA slack channel.

**Comment by chrisdukakis** [comment]
fixed in iri: https://github.com/iotaledger/iri/issues/534
