### ISSUE TITLE
Transactions returned from `iota.api.findTransactionObjects({ bundles: [<oneHash>] }` is not ordered by currentIndex

### ISSUE THREAD

**Issue by transducer** [iotaledger/iota.lib.js#211]
`iota.utils.extractJson` only works with transactions that are sorted by `currentIndex`. When a bundle consists of multiple transactions, the transactions returned by`iota.api.findTransactionsObjects` with searchValues equal to `{ bundles: [transaction.bundle] }` or `iota.api.getBundle(transaction.hash)` sometimes return a list that is not ordered by `currentIndex`.

I don't see why this is, so if anyone can tell me I would be happy to learn.

Suggestions:

- Sort transactions in [`extractJson`](https://github.com/iotaledger/iota.lib.js/blob/master/lib/utils/extractJson.js#L12):
   `const sortedBundle = bundle.sort((a, b) => a.currentIndex - b.currentIndex);`
   Or add a docstring to `extractJson` that explains that the bundle needs to be sorted.
- From `getBundle` return the bundles sorted by `currentIndex`.
- ~Return a list sorted by `currentIndex` from `findTransactionObjects`~ since it can return transactions over multiple bundles this is not a good idea.

**Comment by chrisdukakis** [comment]
Hi @transducer, thank you for reporting! Could you provide an example to reproduce the sorting issue?

**Comment by transducer** [comment]
Well I cannot produce an example for `getBundle` actually. So my suggestion that

>getBundle [should] return the bundles sorted by currentIndex

is already implemented.

It turns out unordered transactions from bundles are only returned from `findTransactionObjects` when searching for one bundle hash. 

I have two tests to demonstrate this behavior. I use Mocha that I installed gloablly with `npm i mocha -g`.

Test that demonstrates `iota.api.getBundle` returns transactions ordered by current index:

```
const IOTA = require('iota.lib.js');  // version "0.4.7"
const { expect } = require('chai'); // version "4.1.2"

const iota = new IOTA({
  provider: 'http://node01.testnet.iotatoken.nl:16265',
});

const depth = 6;
const mwm = 10;


/**
 * Gets the first addresses with security level for seed starting at index 0.
 *
 * @function getAddress
 * @param {string} seed IOTA seed to generate an address for
 * @param {string} amount Amount of addresses to return
 * @param {string} securityLevel Generate addresses with this security level (1, 2 or 3)
 * @returns {Promise} With result or reject with error
 */
function getAddress(seed, amount) {
  return new Promise((resolve, reject) =>
    iota.api.getNewAddress(
      seed,
      { index: 0, total: amount, security: 3 },
      (err, res) => (err ? reject(err) : resolve(res)),
    ));
}

/**
 * Send a message via IOTA.
 *
 * @function send
 * @param {string} seed Our IOTA seed
 * @param {string} receiver IOTA address of receiver
 * @param {JSON} message to send
 * @returns {Promise}
 */
function send(seed, receiver, message) {
  return new Promise((resolve, reject) => {
    const trytes = iota.utils.toTrytes(JSON.stringify(message));
    const transfers = [{ address: receiver, value: 0, message: trytes }];

    iota.api.sendTransfer(seed, depth, mwm, transfers, (err, res) => {
      if (!err) {
        return resolve(res);
      }
      console.log(`Send error: ${err}`);
      return reject(err);
    });
  });
}


/**
 * Gets last received transfer message.
 * NOTE: order is not necessarily chronological, but let's assume it is.
 *
 * @function getLastMessage
 * @param {Object} searchValues List of bundle hashes, addresses, tags or
 *                              approvees (e.g., `{ hashes: ['ABCD'] }`)
 * @returns {JSON} Parsed message or `null` when no received transfers
 */
function getLastMessage(searchValues) {
  return new Promise((resolve, reject) => {
    iota.api.findTransactionObjects(searchValues, (err, transactions) => {
      if (err) return reject(err);
      if (!transactions || transactions.length === 0) return reject(new Error('No transactions retrieved.'));

      const sortedTransactions = transactions.sort((a, b) => b.timestamp - a.timestamp);
      const lastTransaction = sortedTransactions[0];

      // First find the bundle transactions, and its tail transaction (with index 0)
      return iota.api.findTransactionObjects({ bundles: [lastTransaction.bundle] }, (e, txs) => {
        if (e) return reject(e);

        const tail = txs.find(t => t.currentIndex === 0);

        // Then get the bundle by the tail's hash
        return iota.api.getBundle(tail.hash, (bundleE, bundleTxs) => {
          const message = JSON.parse(iota.utils.extractJson(bundleTxs));
          console.log('Transaction order:');
          bundleTxs.map(t => console.log(t.currentIndex));

          return resolve(message);
        });
      });
    });
  });
}

const seed = 'WJUFCQTFHWHAKCW9GAZUNKCCXZBWMOU9MSCLLAGU9HUMHJXBJDONFJONTJT9Z9MIXYIWJFGGDNZW9KHOP';

describe('Iota', () => {
  const genLongMessage = () => ({ data: Array(20000).join('A') });
  const longMessage = genLongMessage(); // does not fit in one transaction

  let receiveAddress;

  before(() =>
    // in the test we send from first address of seed and receive on second
    // address of seed
    getAddress(seed, 2)
      .then(([, secondAddress]) => {
        receiveAddress = secondAddress;
      }));

  describe('send', () => {
    it('should be able to send a message that spans multiple transactions', () =>
      send(seed, receiveAddress, longMessage)
        .then(transactions =>

          expect(transactions).to.be.an('array')));

    it('should be able to retrieve a long message that spans multiple transactions', () =>
      getLastMessage({ addresses: [receiveAddress] })
        .then(messageFromIota =>

          expect(messageFromIota).to.have.property('data').and.to.equal(longMessage.data)));
  });
});
```

Output:

```
$ mocha -g Iota --timeout 30000


  Iota
    send
      ✓ should be able to send a message that spans multiple transactions (8892ms)
Transaction order:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
      ✓ should be able to retrieve a long message that spans multiple transactions (1744ms)


  2 passing (13s)
```

So the transactions are ordered. When the test's `getLastMessage` method is changed to use `iota.api.findTransactionObjects` instead of `iota.api.getBundle` as follows:

```
function getLastMessage(searchValues) {
  return new Promise((resolve, reject) => {
    iota.api.findTransactionObjects(searchValues, (err, transactions) => {
      if (err) return reject(err);
      if (!transactions || transactions.length === 0) return reject(new Error('No transactions retrieved.'));

      const sortedTransactions = transactions.sort((a, b) => b.timestamp - a.timestamp);
      const lastTransaction = sortedTransactions[0];

      return iota.api.findTransactionObjects({ bundles: [lastTransaction.bundle] }, (e, txs) => {
        if (e) return reject(e);

        // Transactions need to be sorted by currentIndex for extractJson to work
        // const sortedTxs = txs.sort((a, b) => a.currentIndex - b.currentIndex);

        // Non sorted:
        const message = JSON.parse(iota.utils.extractJson(txs));
        console.log('Transaction order:');
        txs.map(t => console.log(t.currentIndex));

        return resolve(message);
      });
    });
  });
}
```

Then the test result is:

```
$ mocha -g Iota --timeout 30000


  Iota
    send
      ✓ should be able to send a message that spans multiple transactions (4821ms)
Transaction order:
9
12
6
18
1
13
15
17
4
14
7
11
2
16
8
0
3
5
10
      1) should be able to retrieve a long message that spans multiple transactions


  1 passing (9s)
  1 failing

  1) Iota
       send
         should be able to retrieve a long message that spans multiple transactions:
     AssertionError: Target cannot be null or undefined.
      at getLastMessage.then.messageFromIota (test/iota-test.js:117:43)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

So `iota.api.findTransactionObjects` does not return the transactions of one bundle ordered by `currentIndex`.

This might make sense when you pass it an array of bundle hashes, but when you only retrieve one bundle I don't think it does. Then I expect the bundle transactions to be ordered by `currentIndex` so that it is usable by `extractJson`.

**Comment by transducer** [comment]
Thanks that clears it up for me. 

Because of the reasons you state (that `searchValues` can contain multiple keys which can lead to partial bundles, and that `findTransactionObjects` can return double transactions in the case of a reattached one which `getBundle` does not do), I would not add support for returning an ordered bundle to `findTransactionObjects`.

Issue closed. :)
