### ISSUE TITLE
multisig example broken

### ISSUE THREAD

**Issue by robertkowalski** [iotaledger/iota.lib.js#63]
Hi! I found several issues with the multisig example:

The first issue was introduced with 4462ffe6df64d8a12b89fe9aea844a3e72.  The bug is fixed by  passing the new `initiateTransfer` arguments.

However after fixing this issue, the example breaks in another place for me:

```js
/Users/robert/bitfinex/iota.lib.js/lib/crypto/bundle/bundle.js:121
            sum += (normalizedBundle[i * 27 + j] = Converter.value(Converter.trits(bundleHash.charAt(i * 27 + j))));
                                                                                             ^

TypeError: Cannot read property 'charAt' of undefined
    at Bundle.normalizedBundle (/Users/robert/bitfinex/iota.lib.js/lib/crypto/bundle/bundle.js:121:94)
    at Object.validateSignatures (/Users/robert/bitfinex/iota.lib.js/lib/crypto/signing/signing.js:178:39)
    at Object.validateSignatures (/Users/robert/bitfinex/iota.lib.js/lib/utils/utils.js:344:20)
    at /Users/robert/bitfinex/iota.lib.js/examples/multisig.js:68:64
    at Multisig.addSignature (/Users/robert/bitfinex/iota.lib.js/lib/multisig/multisig.js:343:12)
    at /Users/robert/bitfinex/iota.lib.js/examples/multisig.js:65:23
    at Multisig.addSignature (/Users/robert/bitfinex/iota.lib.js/lib/multisig/multisig.js:343:12)
    at /Users/robert/bitfinex/iota.lib.js/examples/multisig.js:59:19
    at createBundle (/Users/robert/bitfinex/iota.lib.js/lib/multisig/multisig.js:233:20)
    at Multisig.initiateTransfer (/Users/robert/bitfinex/iota.lib.js/lib/multisig/multisig.js:237:11)
```

**Comment by chrisdukakis** [comment]
Thanks for this, example is working in https://github.com/iotaledger/iota.lib.js/pull/58

**Comment by robertkowalski** [comment]
@chrisdukakis thank you, great work!

you seem to have some experience with multisignature wallets. Do you know how to send the finalized bundle to the network? So far my approaches weren't accepted by the network...

**Comment by chrisdukakis** [comment]
You may use `api.sendTrytes()` method.
To get the trytes from the bundle do:
```Javascript
const trytes = [];
bundle.forEach(function(tx) {
    trytes.push(iota.utils.transactionTrytes(tx))
});
iota.api.sendTrytes(trytes.reverse(), depth, mwm, callback);
```

**Comment by todofixthis** [comment]
Possibly related: #48

**Comment by robertkowalski** [comment]
was fixed in https://github.com/iotaledger/iota.lib.js/pull/107
