### ISSUE TITLE
kerl/kerl.js:29  gives me 'Illegal length provided' when using iota.api.sendTransfer

### ISSUE THREAD

**Issue by MichaelSchwab** [iotaledger/iota.lib.js#70]
Sorry but I really dont know whats wrong. I have used the high level function for doing a transfer iota.api.sendTransfer and it worked, then I tried to send the options so that I can control remainder address and funding addresses, there the error happened the fist time. But now it also happens when not using any funding addresses. Anyway this should not happen when using highlevel functions.

Here is the stack trace:
/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/crypto/kerl/kerl.js:29
        throw new Error('Illegal length provided');
        ^

Error: Illegal length provided
    at Kerl.absorb (/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/crypto/kerl/kerl.js:29:15)
    at Bundle.finalize (/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/crypto/bundle/bundle.js:95:14)
    at signInputsAndReturn (/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/api/api.js:1250:16)
    at addRemainder (/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/api/api.js:1215:21)
    at /home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/api/api.js:1166:21
    at /home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/api/api.js:948:28
    at makeRequest.prepareResult (/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/utils/makeRequest.js:189:12)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/mike/projekte/crypto-currencys/iota/node_modules/iota.lib.js/lib/utils/makeRequest.js:61:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/mike/projekte/crypto-currencys/iota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/mike/projekte/crypto-currencys/iota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)

**Comment by chrisdukakis** [comment]
This is because address were passed with checksum in `options`.
Please use `iota.utils.noChecksum()` or just pass addresses without checksum.
We will remove checksum automatically in upcoming release.

**Comment by MichaelSchwab** [comment]
Ok tanks for the very quick answer! Its working now!
